name: Hashnode Blog Posts
on:
  schedule:
      - cron: '0 12 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         comment_tag_name: "BLOGPOSTS"
         feed_list: "https://blogs.achmadk.dev/rss.xml"
         template: "$newline - [$title]($url)"
         commit_message: "recent posts section updated"
         gh_token: ${{ secrets.GITHUB_TOKEN }}
